# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://shangfengding.github.io/
date_format: "GreenHand程序猿"
title: GreenHand程序猿
subtitle: "GreenHand的成长之路"
description: "丁上峰的个人博客"
keywords: 丁上峰, Shangfeng Ding, coding, shangfengding, shangfengding
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shangfeng Ding
organization: 
organization_url: 
github_username: ShangfengDing
location: 北京
email: shangfeng.ding@Outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 博文

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /wiki/
#     label: 维基

  -
    href: /projects/
    label: 项目    

  # -
  #   href: /links/
  #   label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    projects:
        output: true
        permalink: /projects/:path/
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ShangfengDing/ShangfengDing.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ShangfengDing
    repo: comment
    oauth:
        client_id: 8d2855fb79da0f49d187
        client_secret: ce22bc5bb71295cc598f55699f5bb6eecc733b38
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ShangfengDing
    repo: comment
    clientID: 8d2855fb79da0f49d187
    clientSecret: ce22bc5bb71295cc598f55699f5bb6eecc733b38
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-150673330-1
